<?php
// $Id$

/**
 * @file
 * The OGEvents module.
 *
 * This module provides an Active Transportation (walk/bike/other)
 * Challenge event system.  It requires CCK types for school, event,
 * and registrations.
 * @ingroup ogevents
 */

// query returns NIDs of schools (groups) registered for the
// given events (notice the IN (%s) in the query)
define('OGEVENTS_QUERY_REGISTERED_SCHOOLS',
  'SELECT DISTINCT oga.group_nid AS school_nid
  FROM {og_ancestry} oga
  JOIN {content_type_registration} reg ON reg.nid = oga.nid
  JOIN {content_field_eventid} field_eventid ON field_eventid.vid = reg.vid
  JOIN {node} sn ON oga.group_nid = sn.nid
  WHERE field_eventid.field_eventid_nid IN (%s)
  ORDER BY sn.title ASC');

define('OGEVENTS_NUM_WEEKS', 5); // # weeks in an event.

define('OGEVENTS_TALLYING', 1);
define('OGEVENTS_REGISTRATION', 2);

define('OGEVENTS_DEBUG', FALSE);

// TODO - rewrite all href code to use drupal l($text,$path) function
// TODO - use t() on all output
// TODO - rename _functions to _ogevents_functions
// TODO - after we prevent revisions from being used, we wouldn't
//       need {node} in the above, as we'd know we have the latest
//       revision without needing to check node.vid.


// Note: This module doesn't have to be version-aware (it can always
//  use the most recent node revision).  Thus the {node} table
//  gives the most recent nid & vid.  node_revisions will have multiple
//  vid's for any node with multiple revisions, so when we're pulling
//  data we'll want to join {node} and {node_revisions} on (vid). Same
//  for {content_field_eventid} and {content_type_registration}: join
//  on (vid).

// The problem with node revisions is that we're using a (registration)
// node along with organic groups to track which schools are registered
// for which events, and if we make a new revision of a registration node
// we would need to update the og_ancestry table if the event node ref
// field changed from one event to another.
// Solution: do not support node revisions (there is really no reason to).
// TODO: form-alter the Registration node-edit form to disable the
//       revisions section.

/**
 * Debug Msg: print if OGEVENTS_DEBUG is set
 */
function _dm($string) {
  if (OGEVENTS_DEBUG) {
    drupal_set_message($string);
  }
}

function _dpm($thing) {
  if (OGEVENTS_DEBUG) {
    dpm($thing);
  }
}


/**
 * Valid permissions for this module
 * @return array An array of valid permissions
 * Permissions:
 * reports -> can view download links for registered schools
 */
function ogevents_perm() {
  return array('access ogevents content', 'access ogevents reports');
}


/**
 * Implementation of hook_init.
 */
function ogevents_init() {
  drupal_add_css(drupal_get_path('module', 'ogevents')  . '/ogevents.css');
}


/**
 * Implementation of hook_menu
 *
 * This will register the following paths:
 * - event/%event_nid/register (for all event_nids which are current).
 *   The page to register a school for the event given in the url.
 *
 * - event/%event_nid/tally/%school_nid  [callback only]
 *   The page where you record trips for the given event and school. (Newest)
 *
 * - event/%event_nid/results
 *   The final results page w/ a table of all schools and their stats. (Newest)
 *
 * - dashboard
 *   The user's personal dashboard w/ links and info for there schools.
 *
 * Note: This hook is rarely called (for instance, when the module is
 *       first loaded).  Should we call it manually when we need to
 *       register new items (e.g. when we add events)? TODO.
 *       Otherwise they'll only show when we clear the menu cache.
 *
 */
function ogevents_menu() {
  $items = array();
  $event_nids = _get_current_reg_events();
  $tlyids = _get_current_tally_events();

  $items['dashboard'] = array(
        'title' => 'My Schools',
        'description' => 'View and record results',
        'page callback' => 'ogevents_page_dashboard',
        'access arguments' => array('access ogevents content'),
        'weight' => -55, // TODO - don't set this. let sitebuilder do it. (rm after dev finished)
        'file' => 'includes/ogevents.pages.inc',
        );

  $items['duplicates'] = array(
        'title' => 'Duplicate Schools',
        'description' => 'Show duplicate schools',
        'page callback' => 'ogevents_page_duplicates',
        'access arguments' => array('access ogevents reports'),
        'type' => MENU_CALLBACK,
        'file' => 'includes/ogevents.pages.inc',
        );


  foreach ($event_nids as &$event_nid) {
    $items["event/$event_nid/results"] = array(
        'title callback' => '_ogevents_get_results_page_title',
        'title arguments' => array(1),
        'description' => 'Results for all participating schools',
        'page callback' => 'ogevents_page_results',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'file' => 'includes/ogevents.pages.inc',
        );

    $items["event/$event_nid/results/csv"] = array(
        'title' => 'Results CSV Export',
        'description' => 'CSV export of results for all participating schools',
        'page callback' => 'ogevents_page_results_csv',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'includes/ogevents.pages.inc',
        );

    $items["event/$event_nid/register"] = array(
        'title callback' => '_get_reg_page_title',
        'title arguments' => array(1),
        'page callback' => 'ogevents_page_register',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'file' => 'includes/ogevents.pages.inc',
        );

    $items["event/$event_nid/register/csv"] = array(
        'title' => 'Registered Schools CSV Export',
        'description' => 'CSV export of all registered schools',
        'page callback' => 'ogevents_page_registered_csv',
        'page arguments' => array(1),
        'access arguments' => array('access ogevents reports'),
        'type' => MENU_CALLBACK,
        'file' => 'includes/ogevents.pages.inc',
        );
  }

  foreach ($tlyids as &$tly) {
    $items["event/$tly/tally/%"] = array( // Month tally page for given event and school
        'title' => t('Tally Trips'),
        'page callback' => 'ogevents_page_tally',
        'page arguments' => array(1,3),
        'access arguments' => array('access ogevents content'),
        'type' => MENU_CALLBACK,
        'file' => 'includes/ogevents.pages.inc',
        );
    $items["event/$tly/thanks/%"] = array( // tally submission confirmation page
        'title' => t('Thanks!'),
        'page callback' => 'ogevents_page_tally_thanks',
        'page arguments' => array(1,3),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'includes/ogevents.pages.inc',
        );
  }

  return $items;
}

/*
 * Return nids of events open for either registration or tallying.
 * TODO !! sort by tally start date, sooner -> later (in another funct.)
 */
function _ogevents_get_open_events() {
  return array_unique(array_merge(_get_current_reg_events(), _get_current_tally_events()));
}


/**
 * Returns $a and $b in an array with smaller followed by larger.
 */
function _ogevents_util_smallbig($a, $b) {
  return $a < $b ? array($a,$b) : array($b,$a);
}



/**
 * Returns array of nids of schools registered for the given event,
 * where the user is a member of those school OGs.
 */
function _ogevents_get_my_registered_schools($event_nid) {
  global $user;

  $all_registered_schools = _ogevents_get_registered_schools($event_nid);
  if (empty($user->og_groups) || empty($all_registered_schools)) {
    return array();
  } else {
    $registered_groups = array_intersect(array_keys($user->og_groups), $all_registered_schools);

    // Since og_groups may contain schools we registered for a previous event,
    // make sure the current event's registration is owned by us (otherwise it is
    // someone else's event).

    $my_registered_schools = array();
    foreach ($registered_groups as $group_id) {
      $reg_nid = _ogevents_get_registration($event_nid, $group_id);
      $registration = node_load($reg_nid);
      if ($registration->uid == $user->uid) {
        $my_registered_schools[] = $group_id;
      }
    }

    return $my_registered_schools;
  }

  // filter my og schools by event:
  // look for registrations owned by a given user uid.
  //filter_registered_by_user_for_event($my_schools, $event_nid, $user->uid);
  // This SQL does what this function does.  Consider using it instead.
  //SELECT oga.group_nid FROM og_ancestry oga JOIN content_type_registration r ON oga.nid = r.nid JOIN node n ON r.vid = n.vid JOIN content_field_eventid e ON e.vid = r.vid WHERE n.uid = %user AND e.field_eventid_nid = %event
}


function _ogevents_get_school_coordinator_uid($school_nid, $event_nid) {
  $reg_nid = _ogevents_get_registration($event_nid, $school_nid);
  $reg_node = node_load($reg_nid);
  if (! $reg_node->nid) {
    return; // invalid node, no result.
  }
  return $reg_node->uid;
}


/**
 * Returns name (full name if set, or username) of the coordinator for the given school
 * during the specified event.  [Owner of registration node is considered coordinator.]
 * Pre-condition: The given school is registered for the given event.
 *
 * @param $as_link if TRUE, returns name as a link to contact page
                   (with redirect set to return to the current page).
 */
function _ogevents_get_school_coordinator($school_nid, $event_nid, $as_link) {

  $coordinator_uid = _ogevents_get_school_coordinator_uid($school_nid, $event_nid);
  if (! $coordinator_uid) {
   return;
  }

  // get username or profile name
  $coordinator = user_load($coordinator_uid);
  $name = $coordinator->name;
  profile_load_profile($coordinator);
  if (!empty($coordinator->profile_fullname)) {
    $name = $coordinator->profile_fullname;
  }

  if ($as_link) { // show as link if user contact form is enabled.
    // see contact.module _contact_user_tab_access for reference

    global $user;

    // Anonymous users cannot have contact forms,
    // and users can't contact themselves.
    if (!$coordinator->uid ||
         $user->uid == $coordinator->uid) {
      return $name;
    }

    // User admins can contact any user, and
    // users with contact form set can be contacted by other users
    if (user_access('administer users') || !empty($coordinator->contact)) {
      if (!$user->uid) { //anonymous user
        // Here we're assuming logintoboggan will be used to show login for access denied pages
        $title = "Log in to contact coordinator.";
      }
      else {
        $title = "Contact coordinator.";
      }
      //link to contact page, and ensure that after submit,
      //they return here (so we don't need perm. to view user's page).
      return l($name, "user/$coordinator->uid/contact",
               array('attributes' => array('title' => $title),
                     'query' => drupal_get_destination()));
    }
  }

  // If we haven't already returned something, fall back on returning name only
  return $name;
}









/**
 * Returns number in float format with no trailing zeros.
 */
function _ogevents_percentify($num) {
  if ($num == 0) return 0; //handle special case so we don't return an empty string.
  return trim(sprintf("%.1f", $num), ".0");
}



/**
 * Get a unix timestamp for the most recently updated tally or registration
 * for a given school and event.
 * Returns false if no tally data (trips, participation) has been recorded.
 */
function _ogevents_get_latest_tally_timestamp($school_nid, $event_nid) {
  $timestamp = 0;

  $reg_nid = _ogevents_get_registration($event_nid, $school_nid);
  if (!$reg_nid) {
    return FALSE; // no registration, so no tallies either
  }

  $reg_node = node_load($reg_nid);
  if ($reg_node->nid) {
    $staff = $reg_node->field_staff[0]['value'];
    $parents = $reg_node->field_parents[0]['value'];
    $participants = $reg_node->field_participants[0]['value'];
    $studentbody = $reg_node->field_studentbody[0]['value'];
  }

  // consider participation info as tallying activity, use for timestamp
  if ($staff + $parents + $participants + $studentbody > 0) {
    $timestamp = $reg_node->changed;
  }

  // pick out the latest timestamp from the tallies:
  $query = "SELECT n.changed FROM {node} n
  JOIN {content_type_triptally} t ON n.vid = t.vid
  JOIN {og_ancestry} oga ON t.nid = oga.nid
  JOIN {content_field_eventid} e ON t.vid = e.vid
  WHERE oga.group_nid = %d AND e.field_eventid_nid = %d
  ORDER BY n.changed DESC LIMIT 1";
  $tally_time = db_result(db_query($query, $school_nid, $event_nid));

  if ($tally_time > $timestamp) {
    $timestamp = $tally_time;
  }

  return $timestamp;
}



/**
 * Return an array of results for the given school and event
 */
function _ogevents_get_results($school_nid, $event_nid) {

  $biketrips = $walktrips = $othertrips = 0;

  foreach (range(1, OGEVENTS_NUM_WEEKS) as $week) {
    $tally_nid = _ogevents_get_nid_triptally($event_nid, $school_nid, $week);
    if ($tally_nid) {
      $tally_node = node_load($tally_nid);
      // assert tally_node is valid result (s/be, since t_nid is valid).
      $biketrips += $tally_node->field_biketrips[0]['value'];
      $walktrips += $tally_node->field_walktrips[0]['value'];
      $othertrips += $tally_node->field_othertrips[0]['value'];
    }
  }

  $reg_nid = _ogevents_get_registration($event_nid, $school_nid);
  $reg_node = node_load($reg_nid);
  if ($reg_node->nid) {
    $staff = $reg_node->field_staff[0]['value'];
    $parents = $reg_node->field_parents[0]['value'];
    $participants = $reg_node->field_participants[0]['value'];
    $studentbody = $reg_node->field_studentbody[0]['value'];
    $percent = $studentbody ? ($participants / $studentbody * 100) : 0;
  }

  return array('bike_trips' => $biketrips,
               'walk_trips' => $walktrips,
               'other_trips' => $othertrips,
               'staff' => $staff,
               'parents' => $parents,
               'participants' => $participants,
               'studentbody' => $studentbody,
               'student_percentage' => $percent);
}


/**
 * Returns array of NIDs of schools which are registered for the given event(s).
 * If the event is not specified, we return schools registered for any event open for registration.
 * @param events Either a single event NID, an array of event NIDs, or NULL.
 */
function _ogevents_get_registered_schools($event_nids = NULL) {
  if (empty($event_nids)) { // look for schools registered for any event
    $events = _get_current_reg_events();
  } else if (is_array($event_nids)) {
    $events = $event_nids;
  } else {
    $events = array($event_nids);
  }
  $result = db_query(OGEVENTS_QUERY_REGISTERED_SCHOOLS, implode(', ', $events));

  $registered_schools = array();
  while ($row = db_fetch_object($result)) $registered_schools[] = $row->school_nid;

  return $registered_schools;
}


/**
 * Returns true if $sid is a school registered for the specified event.
 */
function _ogevents_is_registered($sid, $event_nids) {
  return array_key_exists($sid, _ogevents_get_registered_schools($event_nid));
}



/**
 * Implementation of hook_theme.
 */
function ogevents_theme($existing, $type, $theme, $path) {
  return array(
    'signin-page' => array(
      'arguments' => array('options' => NULL),
      'template'  => 'signin-form',
    ),
  );
}


function _ogevents_is_tallying_open($event_node) {
  return _ogevents_is_open_for($event_node, OGEVENTS_TALLYING);
}

function _ogevents_is_registration_open($event_node) {
  return _ogevents_is_open_for($event_node, OGEVENTS_REGISTRATION);
}

/**
 * Returns true/false if if the $event_node is open for registration or tallying.
 * @param event: either a numeric node id (nid) or a node
 * @param $window OGEVENTS_REGISTRATION or OGEVENTS_TALLYING (the event window
 *        we're interested in).
 */
function _ogevents_is_open_for($event, $window) {
  $event_node = is_numeric($event) ? node_load($event) : $event;
  if ($window == OGEVENTS_TALLYING) {
    $field = 'field_tallydates';
  }
  else {
    $field = 'field_regdates';
  }

  $today = getdate();
  $UTC_today = $today[0];

    $datefield = $event_node->$field;

    $start_date = $datefield[0]['value'];
    $end_date = $datefield[0]['value2'];

    if (($UTC_today >= $start_date) && ($UTC_today <= $end_date)) {
      return true;
    }
    else {
      return false;
    }

}

/**
 * Return date of tally start
 */
function _ogevents_get_tally_start($event) {
  $event_node = is_numeric($event) ? node_load($event) : $event;
  return $event_node->field_tallydates[0]['value'];
}


/** Get events which are 'current' and published.
 * Current in this context means that today's date is between the 'from' and 'to' component
 * of the specified CCK date field given by name in the parameter $field.
 *
 * @return Array of node IDs.
 */
function _get_current_events($field) {
  $result = db_query("SELECT n.nid FROM {node} n WHERE n.type = 'event' and n.status = 1");
  $nodes = array();
  while ($row = db_fetch_object($result)) {
    $nodes[] = $row->nid;
  }

  $today = getdate();
  $UTC_today = $today[0];
  $current_event_nids = array();

  //check datefield/UTC dates against current date
  foreach ($nodes as $nid) {
    $event_node = node_load($nid);
    $datefield = $event_node->$field;

    $start_date = $datefield[0]['value'];
    $end_date = $datefield[0]['value2'];

    if (($UTC_today >= $start_date) && ($UTC_today <= $end_date)) {
      $current_event_nids[] = $nid;
    }
  }
  return $current_event_nids;
}



/**
 * Get an array of all published Events for which registration is open.
 */
function _get_current_reg_events() {
  return _get_current_events("field_regdates");
}

/**
 * Get an array of all published Events which are now in their tallying period.
 */
function _get_current_tally_events() {
  return _get_current_events("field_tallydates");
}


function _get_reg_page_title($nid) {
  if (count(_get_current_reg_events()) > 1) {
    $node = node_load($nid);
    $title = t("Register your school for $node->title");
  }
  else {
    $title = t('Register your school'); //TODO - Margaux may want this to say 'Register another school', but probably only after we get the big 'Register' link graphic
  }
  return $title;
}

function _get_tally_page_title($nid) {
  $node = node_load($nid);
  $title = t('Tally trips for @school-name', array('@school-name' => $node->title));
  return $title;
}



/**
 * Build a form to register a school for an event.
 * Form contains a single dropdown of unregistered schools.
 */
function ogevents_register_form($form_state, $event_nid) {
  // get nids of schools registered for $event_nid
  $regd_array = _ogevents_get_registered_schools($event_nid);

  $query = "SELECT node.nid AS nid
    FROM {node}
    LEFT JOIN {og} ON node.nid = og.nid
    WHERE node.type = 'school' AND node.status <> 0 AND og.og_directory <> 0
    ORDER BY node.title ASC";
  $result = db_query($query);
  $allgroups = array(); // will be all schools published and listed in the directory
  while ( $obj = db_fetch_object ($result) ) {
    $allgroups[] = $obj->nid;
  }

  $nids = array_diff($allgroups, $regd_array); // array of unregistered schools
  $titles = array();
  foreach ($nids as $nid) {
    $node = node_load($nid);
    $titles[] = t($node->title . " - " . $node->locations[0]['city']) ;
  }

  // build array like (nid -> "<school name> - <city>")
  $first_option = array(-1 => "Select a School...");
  $normal_options = array_combine($nids, $titles);
  $options = $first_option + $normal_options;

  $form['og_register'] = array(
      '#type' => 'select',
      '#title' => t('Select a School'),
      '#multiple' => FALSE,
      '#options' => $options,
      '#required' => TRUE,
      );
  $form['event'] = array('#type' => 'hidden', '#value' => $event_nid);

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Register',
      );

  $form['register_link'] = array(
      '#value' => ' &nbsp; or &nbsp; ' . l('My school doesn\'t appear in the menu or the list below.', 'node/add/school', array('query' => "event=$event_nid")),
      );

  return $form;
}

/**
 * Return the title for the node with the given nid
 */
function _get_node_title($nid) {
  $node = node_load($nid);
  return $node->title;
}


/** Return a template registration node object.
 *  Everything but field_eventid[0]['nid'] is filled in
 */
function _get_blank_regnode() {
  $newNode = (object) NULL;
  $newNode->type = 'registration';
  $newNode->title = 'registration';
  $newNode->uid = $GLOBALS['user']->uid;
  $newNode->created = strtotime("now");
  $newNode->changed = strtotime("now");
  $newNode->status = 1;
  $newNode->comment = 0;
  $newNode->promote = 0;
  $newNode->moderate = 0;
  $newNode->sticky = 0;
  $newNode->field_studentbody[0]['value'] = 0;
  $newNode->field_participants[0]['value'] = 0;
  $newNode->field_staff[0]['value'] = 0;
  $newNode->field_parents[0]['value'] = 0;
  return $newNode;
}

/**
 * Form validate: registering a school
 * Ensures user didn't forget to select school.
 */
function ogevents_register_form_validate($form, &$form_state) {
  $school_picked = $form_state['values']['og_register'];
  if ($school_picked == -1) {
    form_set_error('og_register', t('No school was selected.'));
  }
}

/**
 * Form submit function to register a school.
 *
 * A new 'registration' node is saved which records the event
 * we're signing up for and connects (via og_ancestry table) to
 * the school which had been selected.
 */
function ogevents_register_form_submit($form, &$form_state) {
  $newNode = _get_blank_regnode();
  $newNode->field_eventid[0]['nid'] = $eid = $form_state['values']['event']; //event nid to signup for

  $gid = $form_state['values']['og_register']; // nid of selected school being registered

  node_save($newNode);
  $sql = "INSERT INTO {og_ancestry} (nid, group_nid) VALUES (%d, %d)";
  db_query($sql, $newNode->nid, $gid);

  // clear form storage, to allow form to submit
  $form_state['storage'] = array();

  og_save_subscription($gid, $GLOBALS["user"]->uid, array('is_active' => 1));

  drupal_set_message(_ogevents_get_post_registration_msg($eid));

  $form_state['redirect'] = 'dashboard';
}


/**
 * Remove unnecessary elements (mostly OG stuff) from School node-add form, plus other cleanup.
 */
function _remove_og_extras(&$form) {
  $form['locations'][0]['province']['#pre_render'][] = 'select_province';

  $form['og_private']['#type'] = 'hidden';
  $form['og_description']['#required'] = FALSE;
  $form['og_language']['#type'] = 'hidden';

  unset($form['buttons']['preview']);

  return $form;
}


/**
 * Turn states into a drop-down, and only show OR/WA
 */
function select_province($element) {
  /* If we want all states shown, uncomment this.  But for now we'll just hard-code OR/WA as options.
  $provinces = location_get_provinces('us');
  if (!empty($provinces)) {
    while (list($code, $name) = each($provinces)) {
      $matches[$name] = $name;
    }
  }
  */
  $element['#multiple'] = FALSE;
  $element['#type'] = 'select';
  $element['#options'] = array("Oregon" => "Oregon", "Washington" => "Washington");
  unset($element['#size']);
  return $element;
}

/** Simplify form and change what happens on submit.
 */
function ogevents_form_school_node_form_alter(&$form, &$form_state) {

  $form['#after_build'][] = '_remove_og_extras';
  $form['#submit'][] = 'ogevents_school_form_submit';
  $form['#validate'][] = 'ogevents_form_school_prevent_duplicates_validate';

  if (isset($form_state['post']['name'])) {
    drupal_set_message("Your School has been registered.");
    $form['#redirect'] = 'dashboard';
  }
  return $form;
}


/**
 * Do not allow identical schools (same name/city) from the school-node-add form.
 */
function ogevents_form_school_prevent_duplicates_validate($form, &$form_state) {

    $name = $form_state['values']['title'];
    $city = $form_state['values']['locations'][0]['city'];

    //query for count of identical schools
    $query = "SELECT COUNT(*) FROM {node} n
              JOIN {location_instance} li ON n.nid = li.nid
              JOIN {location} l ON li.lid = l.lid
              WHERE n.title = '%s' AND l.city = '%s'";

    $school_nid = $form_state['values']['nid']; // will be non-empty on updates
    if (!empty($school_nid)) { // when seeking duplicates, ignore this node.
      $query .= " AND n.nid <> $school_nid";
    }

    $count = db_result(db_query($query, $name, $city));

    if ($count > 0) {
      $err_msg = "A school with the same name and city already exists.";
      $event_nid = $_GET['event'];
      if (! empty($event_nid)) {
        $err_msg .= ' <a href="/event/' . $event_nid . '/register">Find it here.</a>';
      }
      form_set_error('edit-title', t($err_msg));
    }
}



function ogevents_school_form_submit($form, &$form_state) {
  // Setup form values so we're ready to add an organic group too.
  $form_state['values']['og_description'] = $form_state['values']['title']; // og desc = <school name>
  $form_state['values']['og_register'] = 0; // don't allow for group joins during user registration
  $form_state['values']['og_private'] = 0; // always public
  $form['locations'][0]['name'] = $form_state['values']['title']; // school location = <school name>
  //TODO: I think location name and og_description could be left blank. (Are they used elsewhere?)
}

/**
 * Returns text to send to drupal_set_message after registering a school.
 */
function _ogevents_get_post_registration_msg($event_nid) {
  return t('Congratulations, your school has been registered. ' .
           'You may log trips via My Schools below, or <a href="@register-page">Register another school</a>.',
           array('@register-page' => url("event/$event_nid/register")));
}

/**
 * Implementation of hook_nodeapi.
 * If school created, insert registration.
 * If school deleted, delete registration and tallies.
 */
function ogevents_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
      if ($node->type == 'school') {
        $newNode = _get_blank_regnode();

        $event_nid = $_GET['event'];
        $newNode->field_eventid[0]['nid'] = $event_nid;
        $gid = $node->nid; //school nid

        if ($event_nid) {
          node_save($newNode);
          $sql = "INSERT INTO {og_ancestry} (nid, group_nid) VALUES (%d, %d)";
          db_query($sql, $newNode->nid, $gid);
          drupal_set_message(_ogevents_get_post_registration_msg($event_nid));
        }
        else {
          drupal_set_message("There's been an error; your school has not been registered.");
        }

        $_REQUEST['destination'] = 'dashboard';
      }
    break;
    case 'delete':
      if ($node->type == 'school') {
        $registrations = _ogevents_get_school_registrations($node->nid);
        // for all events the school registered for,
        //   delete all tallies associated with the school
        //   delete the registration for the event
        foreach ($registrations as $reg_nid) {
          $r_node = node_load($reg_nid);
          _ogevents_delete_tallies($node->nid, $r_node->field_eventid[0]['nid']);
          node_delete($reg_nid);
          drupal_set_message("Deleted registration: $reg_nid");
        }
      }
    break;
  }
}


/**
 * Get IDs of all registrations for the given school.
 * @return array of registration ids.
 */
function _ogevents_get_school_registrations($school_nid) {
  $registrations = array();
  $query = 'SELECT n.nid FROM {node} n '
         . 'JOIN {og_ancestry} oga ON oga.nid = n.nid '
         . 'WHERE n.type = "registration" AND oga.group_nid = %d';
  $res = db_query($query, $school_nid);
  while ($reg_nid = db_result($res)) {
    $registrations[] = $reg_nid;
  }
  return $registrations;
}


/**
 * Delete all tally nodes (content_type_triptally) for
 * the given school and event.
 */
function _ogevents_delete_tallies($school_nid, $event_nid) {
  // get node ids for tallies.
  $query = 'SELECT t.nid FROM {content_type_triptally} t '
         . 'JOIN {content_field_eventid} e ON t.nid = e.nid '
         . 'JOIN {og_ancestry} oga ON t.nid = oga.nid '
         . 'WHERE oga.group_nid = %d AND e.field_eventid_nid = %d';
  $res = db_query($query, $school_nid, $event_nid);
  while ($tally_nid = db_result($res)) {
    node_delete($tally_nid);
    drupal_set_message("Deleted tally: $tally_nid");
  }
}


/**
 * Return a form which gets trip counts for each week.
 */
 /*
function ogevents_month_tally_form($form_state, $event_nid, $gid) {
  $form = array();

  // record participation data
  $reg_nid = _ogevents_get_registration($event_nid, $gid);
  if (!$reg_nid) {
    drupal_set_message("No registration was found for the given school & event ('$gid' and '$event_nid').", 'error');
    return;
  }

  $form['week'] = array(
    '#type' => 'markup',
    '#value' => '<h3>Weekly Totals (optional)</h3>',
    );

  _ogevents_populate_trips_form($form, $event_nid, $gid);

  $form['month'] = array(
    '#type' => 'markup',
    '#value' => '<h3>Monthly Totals (required)</h3>',
    );

  _ogevents_populate_participation_form($form, $reg_nid, $event_nid, $gid);

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Update',
      );

  return $form;
}
*/

/**
 * theme a Drupal fieldset.
 * Copied from core, with only difference is wrapping legend in a span for CSS positioning.
 * XXX BUG TODO: For unknown reason, Drupal is calling the default fieldset theme function
 * and then calling this function, so we get a fieldset within a fieldset, so for the time
 * being I will just move this theme hook to the walknbike theme and look at possible solutions later.
 * Ideas for poss. solutions: 1) create custom #cssified_fieldset form widget which includes
 * the span. 2) Run Drupal in debugger to trace what is happening. 3) Call this theme function
 * from inside form rendering function. (theme_ogevents_month_tally_form).
 *
 * theme_ogevents_fieldset() ...
 */

/**
 * Special theme function for monthly tallying.
 */
 /*
function theme_ogevents_month_tally_form($form) {
  $output .= drupal_render($form);
  return $output;
}
*/

/**
 * Create or update a triptally node.
 * @param gid The school nid.
 * @param week The week we're updating
 * @param bike Number of trips by bike.
 * @param walk Number of trips on foot.
 * @parm other Number of other trips.
 */
function _ogevents_update_triptally($event_nid, $gid, $week, $bike, $walk, $other) {
  // look for the node
  $tally_nid = _ogevents_get_nid_triptally($event_nid, $gid, $week);

  if ($tally_nid) { // use existing node if exists
    $tally_node = node_load($tally_nid);
    _dm("Updating node ($tally_nid) for bike/walk/other values ($bike/$walk/$other) " .
                       "for event/school/week ($event_nid,$gid,$week)."); //DEBUG
  }
  else { // create new node
    if ($bike == 0 && $walk == 0 && $other == 0) { // don't save useless nodes.
      return;
    }

    _dm("Creating new node for bike/walk/other values ($bike/$walk/$other) " .
                       "for event/school/week ($event_nid,$gid,$week)."); //DEBUG

    $is_new_node = TRUE;

    // add node properties
    $tally_node = (object) NULL;
    $tally_node->type = 'triptally';
    $tally_node->title = 'Total Trips';
    $tally_node->uid = $GLOBALS['user']->uid;
    $tally_node->created = strtotime("now");
    $tally_node->changed = strtotime("now");
    $tally_node->status = 1;
    $tally_node->comment = 0;
    $tally_node->promote = 0;
    $tally_node->moderate = 0;
    $tally_node->sticky = 0;

    $tally_node->field_eventid[0]['nid'] = $event_nid;
  }

  // update relevant node bits from function arguments.
  $tally_node->field_week[0]['value'] = $week;
  $tally_node->field_biketrips[0]['value'] = $bike;
  $tally_node->field_walktrips[0]['value'] = $walk;
  $tally_node->field_othertrips[0]['value'] = $other;

  // save.
  node_save($tally_node);
  if (! $tally_node->nid) {
    drupal_set_message("Error saving bike/walk/other values ($bike/$walk/$other) " .
                       "for event/school/week ($event_nid,$gid,$week).", 'error');
  }

  // First time we save the node we need to put in the Org. Group ancestry table too.
  // Note - if we ever get rid of the OG bits we could just store groupid as a node field. (TODO?)
  if ($is_new_node) {
    $sql = "INSERT INTO {og_ancestry} (nid, group_nid) VALUES (%d, %d)";
    db_query($sql, $tally_node->nid, $gid);
  }

  return;
}

/**
 * Submit month participation totals.
 */
function ogevents_participation_form_submit($form, &$form_state) {
  _ogevents_save_participation_form($form_state);
}

function _ogevents_save_participation_form(&$form_state) {
  _dm("form_state: "); //DEBUG
  _dpm($form_state); //DEBUG

  $event_nid = $form_state['values']['event'];
  $school_nid = $form_state['values']['school'];
  $reg_nid = $form_state['values']['regnode']; // the registration for the previously given school+event
  $reg_node = node_load($reg_nid);

  $reg_node->field_participants[0]['value'] = $form_state['values']['participants'];
  $reg_node->field_parents[0]['value'] = $form_state['values']['parents'];
  $reg_node->field_staff[0]['value'] = $form_state['values']['staff'];
  $reg_node->field_studentbody[0]['value'] = $form_state['values']['studentbody'];

  //DEBUG
  _dm("reg node after recording: ");
  _dpm($reg_node);

  node_save($reg_node);

  //DEBUG
  _dm("reg node after saving: ");
  _dpm($reg_node);

  $form_state['redirect'] = "event/$event_nid/thanks/$school_nid";
}



/**
 * Submit tally for the month.
 */
function ogevents_tally_form_submit($form, &$form_state) {

  _dm('tally_form_submit...');
  _dpm($form_state);

  $event_nid = $form_state['values']['event'];
  $gid = $form_state['values']['gid'];

  // for each week, look for info and pass to tally-submit function
  foreach (range(1, OGEVENTS_NUM_WEEKS) as $week) {
    _ogevents_update_triptally($event_nid, $gid, $week,
      $form_state['values']["biketrips$week"],
      $form_state['values']["walktrips$week"],
      $form_state['values']["othertrips$week"]);
  }
}


/**
 * Submit tally for the month and participation info.
 */
/*
function ogevents_month_tally_form_submit($form, &$form_state) {

  _dm('form_state on submit: '); //DEBUG
  _dpm($form_state);

  // save participation bits
  _ogevents_save_participation_form($form_state);

  ogevents_tally_form_submit($form, $form_state);
  return;
}
*/

/**
 * Find the node id of the triptally for the given school, event, week.
 * @param $event_nid The node id of the event we're interested in.
 * @param $gid The school (group) node ID we're interested in.
 * @param $week The week number (1-5) we want.
 * @return nid for desired triptally node.
 */
function _ogevents_get_nid_triptally($event_nid, $gid, $week) {
  $query = "SELECT t.nid FROM {content_type_triptally} t
  JOIN {og_ancestry} oga ON t.nid = oga.nid
  JOIN {content_field_eventid} e ON t.vid = e.vid
  WHERE oga.group_nid = %d AND e.field_eventid_nid = %d AND t.field_week_value = %d";
  // assert - there is only one tally per event/group/week
  return db_result(db_query($query, $gid, $event_nid, $week));
}


/**
 * Returns node id of registration node for given event and school (gid).
 */
function _ogevents_get_registration($event_nid, $gid) {
  $query = "SELECT r.nid
            FROM {og_ancestry} oga
            JOIN {content_type_registration} r ON oga.nid = r.nid
            JOIN {content_field_eventid} e ON r.vid = e.vid
            JOIN {node} n ON n.vid = r.vid
            WHERE n.type = 'registration'
            AND e.field_eventid_nid = %d AND oga.group_nid = %d";
  // assert: there can only be one registration per school+event
  return db_result(db_query($query, $event_nid, $gid));
}






/**
 * A form for recording each week's results for a month.
 */
function ogevents_tally_form($form_state, $event_nid, $gid) {

  $form = array();

  $form['trips'] = array(
      '#type' => 'fieldset',
      //'#title' => t('Weekly Totals (optional)'),
      '#attributes' => array('class' => 'ogevents-tally'),
      //'#collapsible' => FALSE,
      );

  foreach (range(1,OGEVENTS_NUM_WEEKS) as $week) {

    $default_bike = $default_walk = $default_other = 0;

    $tally_nid = _ogevents_get_nid_triptally($event_nid, $gid, $week);
    if ($tally_nid) {
      $tally_node = node_load($tally_nid);
      // assert tally_node is valid result (s/be, since t_nid is valid).
      $default_bike = $tally_node->field_biketrips[0]['value'];
      $default_walk = $tally_node->field_walktrips[0]['value'];
      $default_other = $tally_node->field_othertrips[0]['value'];
    }


    // classes needed for CSS grid trick
    $classes = array('ogevents-hack');
    $classes[] = ($week == 1) ? 'fieldset-header' : 'fieldset-body';
    $classes[] = ($week & 1) ? 'odd' : 'even';

    $form['trips']["week$week"] = array(
        '#type' => 'fieldset',
        '#title' => t('Week !week!or-month',
                      array('!week' => $week,
                            '!or-month' =>
                              $week == OGEVENTS_NUM_WEEKS ? ' or Month Total' : '',
                           )),
        '#attributes' => array('class' => implode(' ', $classes)),
        );


    //$form['trips']["week$week"]["name"] = array('#value' => "<div class=\"foo\">Week $week</div>");

    $form['trips']["week$week"]["walktrips$week"] = array(
        '#type' => 'textfield',
        '#title' => t('Walk'),
        '#default_value' => $default_walk,
        '#size' => 5,
        '#maxlength' => 3,
        '#attributes' => array('class' => 'ogevents-hack'),
        //'#required' => TRUE,
        );

    $form['trips']["week$week"]["biketrips$week"] = array(
        '#type' => 'textfield',
        '#title' => t('Bike'),
        '#default_value' => $default_bike,
        '#size' => 5,
        '#maxlength' => 3,
        '#attributes' => array('class' => 'ogevents-hack'),
        //'#required' => TRUE,
        );

    $form['trips']["week$week"]["othertrips$week"] = array(
        '#type' => 'textfield',
        '#title' => t('Other'),
        '#default_value' => $default_other,
        '#size' => 5,
        '#maxlength' => 3,
        '#attributes' => array('class' => 'ogevents-hack'),
        //'#required' => TRUE,
        );
  }

  $form['event'] = array('#type' => 'hidden', '#value' => $event_nid);
  $form['gid'] = array('#type' => 'hidden', '#value' => $gid);

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Update',
      );

  return $form;
}





//function _ogevents_populate_participation_form(&$form, $reg_nid, $event_nid = NULL, $school_nid = NULL) {
function ogevents_participation_form($form_state, $event_nid, $school_nid) {
  $form = array();

  $reg_nid = _ogevents_get_registration($event_nid, $school_nid);
  $reg_node = node_load($reg_nid);
  _dm("reg_nid in populate_participation_form: $reg_nid"); //DEBUG
  _dm("reg_node in populate_participation_form: <pre>" . print_r($reg_node, TRUE) . "</pre>");

  $studentbody = $reg_node->field_studentbody[0]['value'];
  $participants = $reg_node->field_participants[0]['value'];
  $staff = $reg_node->field_staff[0]['value'];
  $parents = $reg_node->field_parents[0]['value'];

  if ($studentbody + $participants + $staff + $parents > 0) {
    $collapsed = TRUE; //because fields have already been filled out.
  }

  $form['participation'] = array(
      '#type' => 'fieldset',
      //'#title' => t('Participation'),
      //'#collapsible' => TRUE,
      //'#collapsed' => $collapsed,
      '#attributes' => array('class' => 'ogevents-participation'),
      );

/*
  if ($event_nid) { // conditional only needed to still support old day challenge code.  change later...
    $results = _ogevents_get_results($school_nid, $event_nid);
    $bike = $results['bike_trips'];
    $walk = $results['walk_trips'];
    $other = $results['other_trips'];
    $form['participation']['totals'] = array(
      '#type' => 'markup',
      '#value' => "<p>Walk: $walk, Bike: $bike, Other: $other </p>",
      );
  }
  */



  $form['participation']['participants'] = array(
      '#type' => 'textfield',
      '#title' => t('How many students participated (at least one trip) in the Challenge?'),
      '#default_value' => $participants,
      '#size' => 30,
      '#maxlength' => 12,
      '#required' => TRUE,
      );

  $form['participation']['studentbody'] = array(
      '#type' => 'textfield',
      '#title' => t('What is the total student body population at your school?'),
      '#default_value' => $studentbody,
      '#size' => 30,
      '#maxlength' => 12,
      '#required' => TRUE,
      );

  $form['participation']['parents'] = array(
      '#type' => 'textfield',
      '#title' => t('How many parents were involved?'),
      '#default_value' => $parents,
      '#size' => 30,
      '#maxlength' => 12,
      '#required' => TRUE,
      );

  $form['participation']['staff'] = array(
      '#type' => 'textfield',
      '#title' => t('How many teachers/staff were involved?'),
      '#default_value' => $staff,
      '#size' => 30,
      '#maxlength' => 12,
      '#required' => TRUE,
      );

  $form['regnode'] = array('#type' => 'hidden', '#value' => $reg_nid);
  $form['event'] = array('#type' => 'hidden', '#value' => $event_nid);
  $form['school'] = array('#type' => 'hidden', '#value' => $school_nid);

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Submit my Challenge results',
      );

  return $form;
}



